- name: Install docker and docker-compose
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose

- name: Enable and start docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: 'Add {{ username }} to docker group'
  user:
    name: '{{ username }}'
    append: yes
    groups: docker

- name: Install xauth to share display to containers
  apt:
    name: xauth
    state: present
