- name: Enable loop module
  lineinfile:
    dest: /etc/modules-load.d/loop.conf
    line: "loop"
    create: yes

- name: Start loop module
  modprobe:
    name: loop
    state: present

- name: Install docker and docker-compose
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose

- name: Enable and start docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: 'Add {{ username }} to docker group'
  user:
    name: '{{ username }}'
    append: yes
    groups: docker

- name: Install xauth to share display to containers
  pacman:
    name: xorg-xauth
    state: present
