- name: Install python2
  pacman:
    name: '{{ item }}'
    state: present
  with_items:
    - python2
    - python2-virtualenv

- name: Install python3
  pacman:
    name: python
    state: present
