- name: Install sudo
  pacman:
    name: sudo
    state: present

- name: 'Add {{ username }} to sudoers ALL'
  lineinfile:
    dest: /etc/sudoers
    line: "{{ username }} ALL=(ALL) ALL"
    validate: "visudo -cf %s"
